### ISSUE TITLE
[1.20.1] The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bedrockplus'!

### ISSUE THREAD

**Issue by someonedeepintheinternet** [anviaan/BedrockPlus#10]
uh, basically it crashed when booting mc, it mentioned bedrockplus so I came here to receive enlightment. If you need additional config files, please tell me. 
Bedrock mod version: v1.6

crash file:
[crash-2023-09-22_12.56.33-client.txt](https://github.com/anviaan/BedrockPlus/files/12700019/crash-2023-09-22_12.56.33-client.txt)

mod list:
[modlist.txt](https://github.com/anviaan/BedrockPlus/files/12700026/modlist.txt)

**Comment by someonedeepintheinternet** [comment]
oof, I jsut noticed that I have the wrong version. 
Kinda confusing though because:
![temp](https://github.com/anviaan/BedrockPlus/assets/116382854/ce530fa3-de63-482a-9176-c94eab0f7591)

**Comment by mpustovoi** [comment]
Better reopen the issue. The 1.19.4 version is really incompatible with 1.20.1 and that breaks my modpack every time I update it.
