### ISSUE TITLE
The tools all have the same mining speed and attack damage

### ISSUE THREAD

**Issue by Dekooh-Rm** [anviaan/BedrockPlus#14]
Regardless if i change the config file or not, the attack damage and mining speed stay the same for all tools as shown in the attached images.
![image_2024-07-18_063147620](https://github.com/user-attachments/assets/59c77296-430f-4e08-b1b1-319d967e5f39)
![image_2024-07-18_063203347](https://github.com/user-attachments/assets/65e4907e-04de-49b4-a6bd-cdc8570c02a8)
![image_2024-07-18_063220805](https://github.com/user-attachments/assets/78e51269-591f-4807-b877-3a139834f66b)
![image_2024-07-18_063234437](https://github.com/user-attachments/assets/07819612-3a03-481c-acf3-abda051d3f42)
![image_2024-07-18_063244796](https://github.com/user-attachments/assets/76941267-2712-4e95-b1a1-1206af82c107)
![image_2024-07-18_063350547](https://github.com/user-attachments/assets/5bb1e52b-ae8f-4f5e-bfde-1a4601230578)

**Comment by anviaan** [comment]
What version of the mod are you using?
What Loader are you using?
What version of MInecraft are you using>

**Comment by Dekooh-Rm** [comment]
> What version of the mod are you using? What Loader are you using? What version of MInecraft are you using>

Bedrock Plus 1.6
Fabric Loader 16.0
Minecraft 1.21
