### ISSUE TITLE
The config is not applied to the game.

### ISSUE THREAD

**Issue by spinodal23** [anviaan/BedrockPlus#3]
I'm running a server with some mods.
I changed some values in the config file like the following image. Both the config of server and client have the same value.

tools.durability=4275   #int | default: 4062
tools.miningSpeed=10.0d   #double | default: 10.0d
tools.attackDamage=5.0d   #double | default: 5.0d
tools.miningLevel=4   #int | default: 4
tools.enchantability=30   #int | default: 30
sword.attackDamage=7   #int | default: 7
sword.attackSpeed=-1.4d   #double | default: -1.4d
pickaxe.attackDamage=5   #int | default: 5
pickaxe.attackSpeed=-1.8d   #double | default: -1.8d
axe.attackDamage=9   #int | default: 9
axe.attackSpeed=-2d   #double | default: -2d
shovel.attackDamage=5.5   #double | default: 5.5
shovel.attackSpeed=-2d   #double | default: -2d
hoe.attackDamage=0   #int | default: 0
hoe.attackSpeed=1d   #double | default: 1d
armor.durabilityMultiplier=74   #int | default: 74
armor.enchantability=2   #int | default: 2
armor.toughness=4.5d   #double | default: 4.5d
armor.knockbackResistance=0.4d   #double | default: 0.2d
armor.protectionAmounts.0=5   #int | boots | default: 5
armor.protectionAmounts.1=8   #int | leggings | default: 8
armor.protectionAmounts.2=10   #int | breastplate | default: 10
armor.protectionAmounts.3=5   #int |helmet | default: 4

And here's the game screen capture images.

![image](https://user-images.githubusercontent.com/96723542/211196961-94664637-ddfa-4df2-a3f8-ca6c90f29ae0.png)
In the above image, the durability is not applied.

![image](https://user-images.githubusercontent.com/96723542/211197072-144a1348-aec9-4a23-913d-2184e3138668.png)
In the above image, the armor protection amount is not applied.
The knockback resistance is applied.

**Comment by spinodal23** [comment]
I'm using this version: https://www.curseforge.com/minecraft/mc-mods/bedrock-pus/files/3926723

**Comment by spinodal23** [comment]
Sorry for not enough information, I forgot to write.
Fabric Loader 0.14.9
Fabric API: 0.67.1

**Comment by anviaan** [comment]
After an analysis of this situation, also with my other mods, I will add a dependency to make the configuration file, which will be available soon. Let me work on it and thank you! :D

**Comment by spinodal23** [comment]
Thank you :)

**Comment by spinodal23** [comment]
This is a small thing I want to suggest. If a server has the mod and the config is different from the clients', then the clients' armors and tools should follow the server's config.
This isn't right now, and I have to manually share my client's config to other players.

**Comment by anviaan** [comment]
I think I will change my lib. Again 😅

**Comment by spinodal23** [comment]
Thank you for considering my suggestion :)
