### ISSUE TITLE
Crashing w/ Elytra

### ISSUE THREAD

**Issue by TitaniumSkeleton** [anviaan/BedrockPlus#7]
So a friend and I made a server with a few different mods to play with including this one. We progressed a decent bit before heading to the end where he had full bedrock armor (I used a different mod armor) and once we got an elytra, he put it on and crashed and could not join back at all. I had to go to a backup from hours ago, but we managed to make it back and realized that the boots were the only piece of armor that when equipped with an elytra will crash your game and not let you ever rejoin. We made sure he had nothing else modded on him, and he tested each piece of gear and the boots were the only ones that crashed him

**Comment by noah97434** [comment]
hello I install this mod with my friends and work everything very well until we are the eletra has this momant the I so equip the elytra and the game crash and I could not come back on lza survival I would like to know if there is a solution

**Comment by anviaan** [comment]
I have been replicating the error to solve it and I have not been able to, I would like to get more information about the game, if you are using forge or fabric and what version of the mod you have.

**Comment by TitaniumSkeleton** [comment]
I am using forge on 1.20.1 with version 1.20.x-1.4.3

**Comment by anviaan** [comment]
fixed
