### ISSUE TITLE
[Suggestion] Able to disable particles when wearing a full set

### ISSUE THREAD

**Issue by andw20** [anviaan/BedrockPlus#9]
What the title says. I want to be able to disable the resistance particles when wearing a full set but I also want my particles in my settings to still be on. Maybe add an option in the config file to disable it or disable it in general. 

Version I am using
1.5
Fabric, loader version: 0.14.22
1.20.1

**Comment by anviaan** [comment]
soon in version 1.6

**Comment by andw20** [comment]
Thank you very much
